---
- name: "Createing Flavor {{ flavorname }} "
  ignore_errors: no
  os_nova_flavor:
    name: "{{ flavorname }}"
    state: present
    ram: "{{ ram }}"
    vcpus: "{{ vcpus }}"
    rxtx_factor: 1
    is_public: no
    disk: "{{ disk }}"
    extra_specs:
      "hw:vif_multiqueue_enabled": "True"
      "hw:cpu_policy": "dedicated"
      "hw:mem_page_size": 1048576
#      "aggregate_instance_extra_specs: {{ aggregate }}": True
      "hw:cpu_realtime": "yes" 
      "hw:cpu_realtime_mask": '^0'
      "hw:cpu_thread_policy": 'isolate' 	  
    auth:
      auth_url: "{{ auth_url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      project_name: "{{ project_name  }}"
    cacert: "{{ cacert }}"

- name: "Access to flavor = {{ flavorname }} to project = Admin Project"
  ignore_errors: no
  os_project_access:
    state: present
    target_project_id: "{{ admin_project_id }}"
    resource_name: "{{ flavorname }}"
    resource_type: nova_flavor
    auth:
      auth_url: "{{ auth_url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      project_name: "{{ project_name }}"
    cacert: "{{ cacert }}"

