---
- name: "Getting id of project {{ get_project_name }}"
  os_project_facts:
    name: "{{ get_project_name }}"
    auth:
       auth_url: "{{ auth_url }}"
       username: "{{ username }}"
       password: "{{ password }}"
       project_name: "{{ project_name }}"
    cacert: "{{ cacert }}"
  register: projectid
- debug: var=openstack_projects

#- name: "Cleaning Up All Networking Resources Like (Networks,Subnets,Ports,Router Interfaces, Routers, FloatingIP,Secuirity Group)... from project {{ get_project_name }} "
#  shell: "echo 'source /root/openrc' > /tmp/t"


#- name: "Cleaning Up All Networking Resources Like (Networks,Subnets,Ports,Router Interfaces, Routers, FloatingIP,Secuirity Group)... from project {{ get_project_name }} "
#  shell: "chmod +x /tmp/t"



#- name: "Cleaning Up All Networking Resources Like (Networks,Subnets,Ports,Router Interfaces, Routers, FloatingIP,Secuirity Group)... from project {{ get_project_name }} "
#  shell: "sudo /bin/bash /tmp/t "



#- name: "Cleaning Up All Networking Resources Like (Networks,Subnets,Ports,Router Interfaces, Routers, FloatingIP,Secuirity Group)... from project {{ get_project_name }} "
#  raw: "neutron purge {{ projectid.ansible_facts.openstack_projects[0].id }}"

- name: "Cleaning Up All Networking Resources Like (Networks,Subnets,Ports,Router Interfaces, Routers, FloatingIP,Secuirity Group)... from project {{ get_project_name }} "
  raw: ". ~/openrc; neutron purge {{ projectid.ansible_facts.openstack_projects[0].id }}"







#- name: "Fatching info about network {{ network_name }} "
#  os_networks_facts:
#   name: "{{ network_name }}" 
#   auth:
#      auth_url: "{{ auth_url }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#      project_name: "{{ project_name  }}"
#   cacert: "{{ cacert }}"
#  register: result 
#X- debug: var=result.ansible_facts.openstack_networks[0].status
#- debug: var=result.ansible_facts.openstack_networks[0].id

#- name: "Deleting All Orphan Networking Resources Like (Networks,Subnets,Ports,Router Interfaces, Routers, FloatingIP,Secuirity Group)..."
#  shell: "neutron purge {{ result.ansible_facts.openstack_networks[0].id  }}"


#- name: "how to find out instance is with any tenant or not"
#  os_server_facts:
#X   server: "*vm"
#   auth:
#      auth_url: "{{ auth_url }}"
#      username: "{{ username }}"
#      password: "{{ password }}"
#      project_name: "{{ project_name  }}"
#   cacert: "{{ cacert }}"
#  register: project_var
#- debug: var=openstack_servers[0].accessIPv4
#- debug: var=openstack_servers[1].accessIPv4

#- name: "printing things"
#  shell: "echo {{ project_var.ansible_facts.openstack_servers[0].project_id }} > /tmp/t"
