---
- name: "Enable access to flavor = {{ flavorname }} to project = {{ target_project_id }}"
  os_project_access:
    state: present
    target_project_id: "{{ item }}"
    resource_name: "{{ flavorname }}"
    resource_type: nova_flavor
    auth:
      auth_url: "{{ auth_url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      project_name: "{{ project_name }}"
    cacert: "{{ cacert }}"
  with_items: 
    - "{{ target_project_id }}"

