---
- name: "Display Project Detail For {{ proj_name }}"
  os_project_facts:
    name: "{{ proj_name }}"
    auth:
      auth_url: "{{ auth_url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      project_name: "{{ project_name  }}"
    cacert: "{{ cacert }}"
  debug: 
    var: openstack_projects
